# Generated by Django 2.2.10 on 2021-02-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibility',
            name='area',
            field=models.CharField(max_length=55),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
