# Generated by Django 2.2.10 on 2021-03-17 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=34)),
                ('email_address', models.EmailField(max_length=254)),
                ('buying_house', models.CharField(max_length=55)),
                ('first_order', models.DateField()),
                ('last_order', models.DateField()),
                ('phone_number', models.CharField(max_length=21)),
                ('associate_merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.Merchant')),
            ],
        ),
    ]
