# Generated by Django 2.2.10 on 2021-03-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('joining_date', models.DateField()),
                ('resign_date', models.DateField()),
                ('phone_number', models.CharField(max_length=21)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
    ]
