# Generated by Django 2.2.10 on 2021-03-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210317_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('pullover', 'Pullover'), ('cardigan', 'Cardigan'), ('vest', 'Vest')], max_length=21),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
