# Generated by Django 2.2.10 on 2021-03-20 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210320_1222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
